name: IntelliJ Plugin

on:
  push:
    paths:
      - 'src/IntelliJ/**'
      - '.github/workflows/intellij.yml'
  pull_request:
    paths:
      - 'src/IntelliJ/**'
      - '.github/workflows/intellij.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build IntelliJ Plugin
        working-directory: src/IntelliJ
        run: ./gradlew buildPlugin --no-daemon
      - name: Archive plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: intellij-plugin
          path: src/IntelliJ/build/distributions/*.zip
